# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br>

**NumPY stands for? Ans: Numerical Python  
Numpy developed by? Ans: Travis Oliphant**

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>

# Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`
### Methods: `reshape()`, `max()`, `min()`, `argmax()`, `argmin()`<br>
### Attributes: `size, shape, dtype`
### Indexing & slicing of 1-D arrays (vectors)
###  Indexing & slicing 2-D arrays (matrices)

In [2]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [3]:
# Lets create a Python list.
my_list = [-1,0,1]

my_list

[-1, 0, 1]

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [4]:
my_array = np.array(my_list)

my_array

array([-1,  0,  1])

In [5]:
# Lets create and cast a list of list to generate 2-D array
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [6]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matrix_one.shape

(2, 3)

In [8]:
# We can use Tuple instead of list as well.
my_tuple = (-1,0,1)
my_array = np.array(my_tuple)
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [9]:
num = np.arange(100) # similar to range() in Python, not including 100
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# We can give the step
np.arange(3,10,2)

array([3, 5, 7, 9])

In [ ]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [10]:
# start from 1 & end at 15 with 25 evenly spaced points b/w 1 to 15.
np.linspace(1, 15, 25, retstep=True)

(array([ 1.        ,  1.58333333,  2.16666667,  2.75      ,  3.33333333,
         3.91666667,  4.5       ,  5.08333333,  5.66666667,  6.25      ,
         6.83333333,  7.41666667,  8.        ,  8.58333333,  9.16666667,
         9.75      , 10.33333333, 10.91666667, 11.5       , 12.08333333,
        12.66666667, 13.25      , 13.83333333, 14.41666667, 15.        ]),
 0.5833333333333334)

In [ ]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace
# my_linspace[1] to get the stepsize only

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)

In [ ]:
np.linspace(1,2,30) # 1-D array

array([1.        , 1.03448276, 1.06896552, 1.10344828, 1.13793103,
       1.17241379, 1.20689655, 1.24137931, 1.27586207, 1.31034483,
       1.34482759, 1.37931034, 1.4137931 , 1.44827586, 1.48275862,
       1.51724138, 1.55172414, 1.5862069 , 1.62068966, 1.65517241,
       1.68965517, 1.72413793, 1.75862069, 1.79310345, 1.82758621,
       1.86206897, 1.89655172, 1.93103448, 1.96551724, 2.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

In [ ]:
x = np.arange(0, 16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
x.shape

(16,)

In [ ]:
x.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
y = x.reshape(2, 4, 2)

In [ ]:
y.shape

(2, 4, 2)

In [ ]:
x = y.reshape(16)

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x.shape

(1, 16)

## Random

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(4) # 1-D array with three elements

array([0.56857193, 0.70444535, 0.38774413, 0.06367394])

In [ ]:
np.random.rand(6,4)  # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.60525625, 0.2546573 , 0.41268991, 0.16109012],
       [0.54346942, 0.80262832, 0.52027391, 0.88833263],
       [0.94015934, 0.03242477, 0.96564455, 0.74594476],
       [0.82275534, 0.01635633, 0.584864  , 0.08268238],
       [0.07011841, 0.22109206, 0.85855401, 0.52235779],
       [0.42877327, 0.9725418 , 0.94471874, 0.35214834]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [11]:
np.random.randn(10, 5)

array([[-0.94960787,  1.19970512,  0.9049603 , -0.8517187 ,  0.45453704],
       [-0.2476404 ,  0.33545753, -0.43177982,  0.63709754,  1.66193455],
       [-0.75686322,  0.86345089, -0.81111908,  1.93261776,  0.03136084],
       [ 0.98525567, -0.18016219, -0.43962798, -0.76115741, -1.12778204],
       [-1.16467434, -0.299979  ,  0.49763652,  0.1660593 ,  0.71330383],
       [ 0.53830306, -0.85998762,  1.31027839, -0.41498643,  1.54193199],
       [-0.98027525, -0.85480462, -0.70091945, -3.12566871, -0.86613976],
       [ 0.87874431,  0.41652216,  1.29375787, -0.24180924,  1.60647464],
       [ 0.98501193, -0.25546539, -0.98384724, -0.86866281, -1.93944459],
       [-0.96341501, -1.66073609, -0.79233099, -1.87365177,  0.76978549]])

In [ ]:
normal_array = np.random.randn(1000,1) # no tuple, each dimension as a separate argument
normal_array

In [ ]:
import pandas as pd

df = pd.DataFrame(data=normal_array, columns=['A'])
df

In [ ]:
df['A'].hist(bins=100)

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(100, 200, 20) #returns one random int, 1 inclusive, 100 exclusive

array([191, 134, 165, 134, 155, 109, 120, 162, 126, 173, 133, 131, 106,
       139, 193, 154, 195, 132, 179, 190])

In [ ]:
np.random.randint(100,200,20).reshape(4,5) #returns ten random int,

array([[150, 136, 173, 177, 192],
       [157, 191, 174, 174, 183],
       [102, 150, 101, 171, 114],
       [148, 124, 163, 173, 147]])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [ ]:
# lets create 2 arrays using arange() and randint()
array_ranint = np.random.randint(0,100,10)

In [ ]:
array_ranint

array([98, 23,  7, 84, 16,  8, 87, 35, 20, 84])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [ ]:
array_ranint

array([98, 23,  7, 84, 16,  8, 87, 35, 20, 84])

In [ ]:
array_ranint.min()

7

In [ ]:
array_ranint.max()

98

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [ ]:
array_ranint.argmax() # index starts from 0

0

In [ ]:
array_ranint.argmin()

2

### Attributes
* `size, shape, dtype`

In [ ]:
array_arange=np.arange(16)

In [ ]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# Lets take vector array, array_arange
array_arange.shape
#reshape_test.shape

(16,)

In [ ]:
array_arange.size

16

In [ ]:
# Size of the array
array_arange.itemsize

4

In [ ]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [ ]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
array_arange.shape = (4,4)

In [ ]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
array_arange.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
array_arange.reshape(1,16).shape

### Indexing & slicing of 1-D arrays (vectors)

In [ ]:
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [ ]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [ ]:
array_1d[2]

0

In [ ]:
# Getting a range value
array_1d[0:3]

array([-10,  -2,   0])

In [ ]:
# Using -ve index
array_1d[-2]

106

In [ ]:
# Using -ve index for a range
array_1d[1:-2]

array([-2,  0,  2, 17])

In [ ]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [ ]:
array_1d[:2]

array([-10,  -2])

In [ ]:
array_1d[2:]

array([  0,   2,  17, 106, 200])

In [ ]:
# Assigning a new value to a certain index in the array
array_1d[0] = -102

In [ ]:
array_1d
# The first element is changed to -102

array([-102,   -2,    0,    2,   17,  106,  200])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [ ]:
array_2d = np.arange(24)
array_2d = array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br>
* **`array_2d[row,col]`**.

We will use `[row,col]`, easier to use comma ',' for clarity.

In [ ]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [ ]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [ ]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# another way
row = 5
column = 2
array_2d[row, column]

22

In [ ]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

22

In [ ]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# 2D array slicing
array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

### Broadcasting

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>

**Lets start with some simple examples:**

In [ ]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [ ]:
array_1d[0:5] = 500
array_1d

In [ ]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4), dtype=int)
array_2d

In [ ]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

In [ ]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why?

In [ ]:
array_2d

In [ ]:
array_2d * np.arange(0,4)

In [ ]:
array_2d + 300
# array_2d + [300,2], did it work? if not why?

In [ ]:
array_2d

In [ ]:
array_2d[[3, 1]]

In [ ]:
array_2d[:,[2]]

In [ ]:
array_2d

In [ ]:
# We can use any order
array_2d[[3, 1]]

In [ ]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

In [ ]:
# grabbing rows
array_2d[[2,3]] #[2][3]

In [ ]:
array_2d[:3, [2,3]]

In [ ]:
# grabbing columns
#array_2d[:,3:2]
array_2d[:,[3,2]]

In [ ]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

We can apply condition such as >, <, == etc

In [ ]:
array_1d > 3

In [ ]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

Lets create a mask to **filter out the even numbers in "array_1d"**

In [ ]:
array_1d % 2

In [ ]:
0 == array_1d % 2

In [ ]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = array_1d % 2 != 0
mod_2_mask_1d

In [ ]:
array_1d

In [ ]:
array_1d[mod_2_mask_1d] #array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]]

## NumPy Operations

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 2.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>


## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [ ]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr

In [ ]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

In [ ]:
# Subtracting two arrays
arr - arr

In [ ]:
# Multiplication
arr * arr

In [ ]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

In [ ]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

In [ ]:
# Power of all the elements in an array
arr ** 2

In [ ]:
# Multiplication with scalar
2 * arr #[0, 1, 2, 3, 4]

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [ ]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

In [ ]:
# max and min values
np.max(arr), np.min(arr)

In [ ]:
arr.max()

In [ ]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [ ]:
#18a:
# To avoid overwriting the output, please code here

In [ ]:
array_2d= np.arange(30).reshape(6,5)
array_2d

**Calculate the sum of all the numbers in array_2d?**

In [ ]:
array_2d.sum()

In [ ]:
array_2d.sum(axis=1)

**Calculate sum of all the rows and columns in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

**Calculate the standard deviation of the values in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
array_2d.std()

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
array_2d

In [ ]:
array_2d % 3 == 0

In [ ]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

In [ ]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

In [ ]:
np.zeros(5)